---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springbootingg                  # Ingress name
  labels:
    app: springbootingg
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "springbootingg.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springbootingg               # Links to Service name dynamically
                port:
                  number: 8080  # Links to service port dynamically
